version: 2
jobs:

  test-py2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install pytest future && pytest tests
  test-py3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install pytest future && pytest tests


workflows:
  version: 2
  build_and_test:
    jobs:
      - test-py2.7
      - test-py3.6